# Generated by Django 4.2.6 on 2023-10-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('barcode', models.IntegerField(null=True, verbose_name='Barcode')),
                ('year', models.DateField(null=True, verbose_name='Date')),
                ('genre', models.CharField(max_length=255, null=True, verbose_name='Genre')),
                ('rating', models.IntegerField(null=True, verbose_name='Rating')),
                ('runTime', models.IntegerField(null=True, verbose_name='Run Time')),
                ('director', models.CharField(max_length=255, null=True, verbose_name='Director')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='Description')),
            ],
        ),
    ]
