# Generated by Django 4.2.6 on 2023-10-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='score',
            field=models.IntegerField(null=True, verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.CharField(max_length=5, null=True, verbose_name='Rating'),
        ),
    ]
