# Generated by Django 4.2.6 on 2023-11-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_movie_score_alter_movie_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(blank=True, verbose_name='Year'),
        ),
    ]
