# Generated by Django 4.2.6 on 2023-11-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_movie_name2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='name2',
            field=models.CharField(blank=True, max_length=255, verbose_name='name2'),
        ),
    ]
