# Generated by Django 4.2.6 on 2023-10-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_alter_movie_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='barcode',
            field=models.IntegerField(null=True, verbose_name='Barcode'),
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=255, null=True, verbose_name='Director'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(max_length=255, null=True, verbose_name='Genre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(null=True, verbose_name='Rating'),
        ),
        migrations.AddField(
            model_name='movie',
            name='runTime',
            field=models.IntegerField(null=True, verbose_name='Run Time'),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
    ]
